# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_dev_utils"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_lexar"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_mir"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_mir_parser"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_mir_syntax"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_session"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wiz_syntax"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wizc"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/wiz/wizc_cli"
    schedule:
      interval: "daily"
