version: '2'

services:
  builder:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: rust
    volumes:
      - ./:/wiz
    environment:
      RUST_BACKTRACE: full
    working_dir: /root/
  wiz:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: wiz
    volumes:
      - ./out/:/out/
    environment:
      RUST_BACKTRACE: full
    working_dir: /out/
