version: '2'

services:
  builder:
    build:
        context: .
        dockerfile: ./Dockerfile
    volumes:
        - ./:/wiz
    working_dir: /wiz/wiz/wizc
    command: /root/.cargo/bin/cargo run /wiz/helloworld.wiz
