[package]
name = "wizc_message"
version = "0.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
