[package]
name = "wiz_session"
version = "0.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wizc_cli = { path = "../wizc_cli" }
wizc_message = { path = "../wizc_message" }
