name: Build
on:
  push:
    branches:
      - main
      - ci/*

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: echo rust version
        run: rustc --version
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: ${{ runner.os }}-llvm-14
      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            wiz/target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        if: runner.os != 'Windows'
      - name: Install LLVM and Clang
        run: |
          if [ ! -d "$FILE" ]; then
            echo "$LLVM_DOWNLOAD_URL"
            curl -L "$LLVM_DOWNLOAD_URL" --output ./llvm.zip
            unzip -o ./llvm.zip -d ./llvm
          fi
        shell: bash
        env:
          LLVM_DOWNLOAD_URL: "https://github.com/wiz-language/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6-windows-binary.zip"
          FILE: ./llvm
        if: runner.os == 'Windows'
      - name: Set Path of LLVM and Clang
        run: |
          echo LLVM_SYS_140_PREFIX="$(dirname $(dirname "$(find $PWD | grep -i bin/llvm-config.exe)"))"
          echo LLVM_SYS_140_PREFIX="$(dirname $(dirname "$(find $PWD | grep -i bin/llvm-config.exe)"))" >> $GITHUB_ENV
        shell: bash
        if: runner.os == 'Windows'
      - name: run build
        run: cargo build --manifest-path wiz/Cargo.toml --release
        shell: bash
        env:
          RUST_BACKTRACE: 1
      - name: create archive
        run: |
          tar cvzf wiz-${{ runner.os }}.tar.gz ./install.sh ./env ./wiz/target/release/wiz ./wiz/target/release/wizc ./libraries
        if: runner.os != 'Windows'
      - name: create archive
        run: |
          tar cvzf wiz-${{ runner.os }}.tar.gz ./install.sh ./env ./wiz/target/release/wiz.exe ./wiz/target/release/wizc.exe ./libraries
        if: runner.os == 'Windows'
      - uses: actions/upload-artifact@v4
        with:
          name: wiz-${{ runner.os }}
          path: |
            wiz-${{ runner.os }}.tar.gz

  pre_release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download linux archive
        uses: actions/download-artifact@v4
        with:
          path: ~/artifact/
      - name: ls
        run: |
          ls ~/artifact/
      - uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: dev-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "~/artifact/**/*"
          tag: dev-latest
          replacesArtifacts: true
          prerelease: true
          token: '${{ secrets.GITHUB_TOKEN }}'
