name: Build
on:
  push:
    branchies:
      - main
      - ci/*

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: echo rust version
        run: rustc --version
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: ${{ runner.os }}-llvm-13
      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            wiz/target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: run build
        run: cargo build --manifest-path wiz/Cargo.toml --release
        env:
          RUST_BACKTRACE: 1
      - uses: actions/upload-artifact@v3
        with:
          name: wiz-${{ runner.os }}
          path: |
            ./wiz/target/release/wiz
            ./wiz/target/release/wizc

  where:
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: where llvm
        run: where llvm-*
