name: Format
on:
  push:

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target          
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: run format wizc
        run: cd wiz && cargo fmt
      - name: run format wiz_syntax
        run: cd wiz/wiz_syntax && cargo fmt
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.4.0
        with:
          author_name: GitHub Actions
          author_email: 41658782+ChanTsune@users.noreply.github.com
          message: "Format commit"
          add: "wiz/*.rs"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
