name: Format
on:
  push:

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.4.0
      - name: run format wiz
        run: cd wiz/wiz && cargo fmt
      - name: run format wizc
        run: cd wiz/wizc && cargo fmt
      - name: run format wiz_lexar
        run: cd wiz/wiz_lexar && cargo fmt
      - name: run format wiz_syntax
        run: cd wiz/wiz_syntax && cargo fmt
      - name: run format wiz_mir
        run: cd wiz/wiz_mir && cargo fmt
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.4.0
        with:
          author_name: GitHub Actions
          author_email: 41658782+ChanTsune@users.noreply.github.com
          message: "Format commit"
          add: "wiz/*.rs"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
