name: Format
on:
  push:

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: run format
        run: cargo fmt --manifest-path wiz/Cargo.toml --all
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41658782+ChanTsune@users.noreply.github.com
          message: "Format commit"
          add: "wiz/*.rs"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
