name: Format
on:
  push:

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.4.0
      - name: run format
        run: find wiz -type f -name '*.toml' | xargs -I {} cargo fmt --manifest-path {}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          author_name: GitHub Actions
          author_email: 41658782+ChanTsune@users.noreply.github.com
          message: "Format commit"
          add: "wiz/*.rs"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
